# Generated by Django 3.2 on 2021-04-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('topics', models.CharField(max_length=128)),
                ('likes', models.IntegerField(default=0)),
                ('video', models.FileField(upload_to='%Y/%m/%d')),
            ],
        ),
    ]
