# Generated by Django 3.2 on 2021-04-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20210426_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='zxzxzx'),
            preserve_default=False,
        ),
    ]
