# Generated by Django 3.2 on 2021-04-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
        migrations.AddField(
            model_name='video',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=17815277129),
            preserve_default=False,
        ),
    ]
