# Generated by Django 3.2 on 2021-05-01 06:36

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_auto_20210429_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='video',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'wmv', 'ogg', 'mov'])]),
        ),
    ]
